---
- name: Add MongoDB Community Edition repository
  yum_repository:
    name: "mongodb-{{ mongodb_version }}"
    description: "Official MongoDB {{ mongodb_version }} Community Edition repository"
    baseurl: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_version }}/x86_64/"
    gpgcheck: yes
    gpgkey: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution'] != 'Fedora'

- name: Add MongoDB Community Edition repository
  yum_repository:
    name: "mongodb-{{ mongodb_version }}"
    description: "Official MongoDB {{ mongodb_version}} Community Edition repository"
    baseurl: "https://repo.mongodborg/yum/redhat/8/mongodb-org/{{ mongodb_version }}/x86_64"
    gpgcheck: yes
    gpgkey: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
  when: ansible_facts['distribution'] == 'Fedora'

- block:
    - name: Install MongoDB Community Edition
      yum:
        name: mongodb-org
        update_cache: yes
      notify:
        - restart MongoDB server

    - name: Enable MongoDB Community Edition service
      systemd:
        name: mongod
        state: started
        enabled: yes
  when: ansible_facts['os_family'] == 'RedHat'

- block:
    - name: Install MongoDB server
      apt:
        name: mongodb
        update_cache: yes
      notify:
        - restart MongoDB server

    - name: Enable MongoDB server service
      service:
        name: mongodb
        state: started
        enabled: yes
  when: ansible_facts['os_family'] == 'Debian'
