---
- name: Keep system up-to-date
  yum:
    name: '*'
    state: latest
    update_cache: yes
  when: ansible_facts['os_family'] == 'RedHat'

- name: Keep system up-to-date
  apt:
    update_cache: yes
    upgrade: dist
  when: ansible_facts['os_family'] == 'Debian'

- name: Install PIP
  package:
    name:
      - python3
      - python3-pip

- name: Install PyMongo
  pip:
    name: pymongo

- name: Add MongoDB Community Edition repository
  yum_repository:
    name: "mongodb-{{ mongodb_version }}"
    description: "Official MongoDB {{ mongodb_version }} Community Edition repository"
    baseurl: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ mongodb_version }}/x86_64/"
    gpgcheck: yes
    gpgkey: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution'] != 'Fedora'

- name: Add MongoDB Community Edition repository
  yum_repository:
    name: "mongodb-{{ mongodb_version }}"
    description: "Official MongoDB {{ mongodb_version }} Community Edition repository"
    baseurl: "https://repo.mongodb.org/yum/redhat/8/mongodb-org/{{ mongodb_version }}/x86_64"
    gpgcheck: yes
    gpgkey: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
  when: ansible_facts['distribution'] == 'Fedora'

- block:
    - name: Install MongoDB Community Edition
      yum:
        name: mongodb-org
        update_cache: yes

    - name: Create data directory
      file:
        path: /data/db
        owner: root
        group: root
        mode: '0644'
        state: directory

    - name: Enable MongoDB Community Edition service
      systemd:
        name: mongod
        state: restarted
        enabled: yes

    - name: Add admin user
      mongodb_user:
        database: admin
        name: "{{ db_user }}"
        password: "{{ key_store_password }}"
        roles: root

    - name: Change binding IP address
      replace:
        path: /etc/mongod.conf
        regexp: '^bind_ip = 127.0.0.1$'
        replace: 'bind_ip = 0.0.0.0'

    - name: Enable authentication
      replace:
        path: /etc/mongod.conf
        regexp: '^#auth = true$'
        replace: 'auth = true'

    - name: Enable MongoDB Community Edition service
      systemd:
        name: mongod
        state: restarted
        enabled: yes
  when: ansible_facts['os_family'] == 'RedHat'

- block:
    - name: Install MongoDB server
      apt:
        name: mongodb
        update_cache: yes

    - name: Create data directory
      file:
        path: /data/db
        owner: root
        group: root
        mode: '0644'
        state: directory

    - name: Enable MongoDB server service
      command: service mongodb restart

    - name: Add admin user
      mongodb_user:
        database: admin
        name: "{{ db_user }}"
        password: "{{ key_store_password }}"
        roles: root

    - name: Change binding IP address
      replace:
        path: /etc/mongodb.conf
        regexp: '^bind_ip = 127.0.0.1$'
        replace: 'bind_ip = 0.0.0.0'

    - name: Enable authentication
      replace:
        path: /etc/mongodb.conf
        regexp: '^#auth = true$'
        replace: 'auth = true'

    - name: Enable MongoDB server service
      command: service mongodb restart
  when: ansible_facts['os_family'] == 'Debian'
