---
galaxy_info:
  author: Alan Tai
  role_name: adoptopenjdk
  description: Install and configure AdoptOpenJDK on RHEL/CentOS-based and Ubuntu systems
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - xenial
    - name: Debian
      version:
        - 10
        - 9
    - name: Fedora
      versions:
        - 30
        - 31
        - 32
    - name: EL
      versions:
        - 6
        - 7
        - 8
  galaxy_tags:
    - java
    - jdk
    - openjdk
    - adoptopenjdk
    - openj9
dependencies: []
