version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Manila
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: react
    versions:
    - ">= 17.a, < 18"
  - dependency-name: ra-i18n-polyglot
    versions:
    - 3.12.0
    - 3.12.1
    - 3.12.4
    - 3.12.5
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
    - 3.13.5
    - 3.14.0
    - 3.14.1
    - 3.14.2
    - 3.14.3
    - 3.14.4
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.3
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.8.1
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.12
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.7
    - 13.1.1
    - 13.1.2
    - 13.1.5
  - dependency-name: ra-test
    versions:
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
    - 3.13.5
    - 3.14.0
    - 3.14.1
    - 3.14.2
    - 3.14.3
    - 3.14.4
  - dependency-name: ra-language-english
    versions:
    - 3.12.0
    - 3.12.1
    - 3.12.4
    - 3.12.5
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
    - 3.13.5
    - 3.14.0
    - 3.14.1
    - 3.14.2
    - 3.14.3
    - 3.14.4
  - dependency-name: react-admin
    versions:
    - 3.12.0
    - 3.12.1
    - 3.12.4
    - 3.12.5
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
    - 3.13.5
    - 3.14.0
    - 3.14.1
    - 3.14.2
    - 3.14.3
    - 3.14.4
  - dependency-name: ra-core
    versions:
    - 3.12.0
    - 3.12.1
    - 3.12.4
    - 3.12.5
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
    - 3.13.5
    - 3.14.0
    - 3.14.1
    - 3.14.2
    - 3.14.3
    - 3.14.4
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.5
    - 11.2.6
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
  - dependency-name: react-detect-offline
    versions:
    - 2.4.2
    - 2.4.3
  - dependency-name: react-scripts
    versions:
    - 4.0.2
    - 4.0.3
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    timezone: Asia/Manila
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: com.amazonaws:aws-java-sdk-bom
    versions:
    - 1.11.1000
    - 1.11.1001
    - 1.11.1002
    - 1.11.1004
    - 1.11.1006
    - 1.11.946
    - 1.11.950
    - 1.11.951
    - 1.11.952
    - 1.11.954
    - 1.11.955
    - 1.11.956
    - 1.11.957
    - 1.11.959
    - 1.11.960
    - 1.11.961
    - 1.11.962
    - 1.11.965
    - 1.11.967
    - 1.11.969
    - 1.11.970
    - 1.11.971
    - 1.11.972
    - 1.11.974
    - 1.11.975
    - 1.11.977
    - 1.11.978
    - 1.11.979
    - 1.11.980
    - 1.11.982
    - 1.11.986
    - 1.11.988
    - 1.11.990
    - 1.11.991
    - 1.11.992
    - 1.11.993
    - 1.11.995
    - 1.11.996
    - 1.11.998
  - dependency-name: org.json:json
    versions:
    - "20210307"
  - dependency-name: com.github.spotbugs
    versions:
    - 4.6.1
    - 4.6.2
    - 4.7.0
  - dependency-name: com.github.ben-manes.versions
    versions:
    - 0.38.0
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.15
    - 3.7.16
    - 3.7.18
    - 3.8.0
    - 3.8.1
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.1
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.1
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 4.9.1
