---
galaxy_info:
  author: Alan Tai
  role_name: system
  description: Configure system parameters in RHEL/CentOS-based and Ubuntu systems
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - xenial
  galaxy_tags:
    - system
    - tuning
dependencies: []
