---
galaxy_info:
  author: Alan Tai
  role_name: mongodb
  description: Configure MongoDB server on RHEL/CentOS-based and Ubuntu systems
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - xenial
    - name: Fedora
      versions:
        - 30
        - 31
        - 32
    - name: EL
      versions:
        - 6
        - 7
        - 8
  galaxy_tags:
    - mongodb
    - nosql
    - database
dependencies: []
