---
- name: Restart MongoDB Community Edition service
  service:
    name: mongodb
    state: restarted
  listen: restart MongoDB server
  when:
    - ansible_facts['os_family'] == 'Debian'
    - service_default_state | default('started') == 'started'

- name: Restart MongoDB Community Edition service
  systemd:
    name: mongod
    state: restarted
  listen: restart MongoDB server
  when: ansible_facts['os_family'] == 'RedHat'
