---
- hosts: all
  become: yes
  vars:
    system_domain_name: "{{ domain_name }}"
    system_ip_address: "{{ ip_address }}"
    ntp_enabled: yes
    ntp_timezone: Asia/Hong_Kong
    instrumentald_mongodb_urls:
      - mongodb://localhost:27017
    certbot_create_if_missing: yes
    certbot_admin_email: "{{ certbot_email }}"
    certbot_certs:
      - domains:
          - "{{ domain_name }}"
          - "{{ random }}.{{ domain_name }}"
    certbot_auto_renew_options: "--quiet --no-self-upgrade --post-hook {{ ansible_env.HOME }}/regenerate.sh"
    certbot_create_standalone_stop_services: []
    security_fail2ban_enabled: yes
    ssl_key_store_path: "/etc/letsencrypt/live/{{ domain_name }}/keystore.p12"
  roles:
    - system
    - geerlingguy.ntp
    - mongodb
    - ayltai.adoptopenjdk
    - ayltai.instrumentald
    - geerlingguy.certbot
    - geerlingguy.security
    - hknews
