name: CD
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Build JavaScript and Java
        run: ./gradlew buildAll
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: bootJar
          path: build/libs/hknews-2.3.1.jar
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Download Java artifact
        uses: actions/download-artifact@v2
        with:
          name: bootJar
          path: src/main/ansible/roles/hknews/files/
      - name: Create Terraform credentials file
        run: 'echo "$TF_CLI_CONFIG_FILE" > src/main/terraform/.terraformrc'
        env:
          TF_CLI_CONFIG_FILE: ${{ secrets.TF_CLI_CONFIG_FILE }}
      - name: Create Terraform variables file
        run: 'echo "$TERRAFORM_VARIABLES" > src/main/terraform/secrets.tfvars'
        env:
          TERRAFORM_VARIABLES: ${{ secrets.TERRAFORM_VARIABLES }}
      - name: Deploy application
        run: ./gradlew applyTerraform
      - name: Upload private key
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: private-key
          path: src/main/terraform/hknews.pem
