name: Terraform
on: [push]
jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build Java
        run: ./gradlew packageZip
      - name: Save Java package
        uses: actions/upload-artifact@v2
        with:
          name: java-package
          path: build/distributions/hknews.zip
  terraform:
    needs:
      - build-java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform 0.14
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.x
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Initialize
        run: terraform init -lock-timeout=600s
        working-directory: src/main/terraform
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: main
      - name: Format
        run: terraform fmt -check
        working-directory: src/main/terraform
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: main
      - name: Valdiate
        run: terraform validate -no-color
        working-directory: src/main/terraform
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: main
      - name: Load Java package
        uses: actions/download-artifact@v2
        with:
          name: java-package
          path: build/distributions
      - name: Create Terraform variable file
        run: 'echo "$TERRAFORM_VARIABLES" > src/main/terraform/secrets.tfvars'
        env:
          TERRAFORM_VARIABLES: ${{ secrets.TERRAFORM_VARIABLES }}
      - name: Plan
        run: terraform plan -lock-timeout=600s -var-file=secrets.tfvars -no-color
        working-directory: src/main/terraform
        env:
          TF_IN_AUTOMATION: true
          TF_WORKSPACE: main
