name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Java unit tests
        run: ./gradlew test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Save Java unit test report
        uses: actions/upload-artifact@v2
        with:
          name: java-test-report
          path: build/reports/tests/test/
      - name: Save Checkstyle report
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle-report
          path: build/reports/checkstyle/
      - name: Save SpotBugs report
        uses: actions/upload-artifact@v2
        with:
          name: spotbugs-report
          path: build/reports/spotbugs/
      - name: Generate Java test coverage report
        run: ./gradlew jacocoTestReport
      - name: Save Java test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: java-test-coverage
          path: build/reports/jacoco/
      - name: Set up Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Run JavaScript unit tests
        run: npm test
      - name: Save JavaScript test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: javascript-test-coverage
          path: coverage/
      - name: Run SonarQube scanner
        run: ./gradlew sonarqube
        if: ${{ always() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
